### ISSUE TITLE
JokesnList

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#1]
## Value Proposition

**As a** user
**I want to** ... to see a list of jokes 
**in order to** ... decide with joke is funny
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] the list shows all available jokes
- [ ] list is scrollable

      ​

## Tasks

- [ ] list the coding tasks that need to be performed
- [ ] create branch `feature/jokelist`
- [ ] create component JokeList
- [ ] create Tests for JokeList component
