### ISSUE TITLE
US - Medication Reminder Feature Implementation

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#14]
## Value Proposition

**As a** user
**I want to** receive reminders for taking medication to ensure
**so that** I don´t miss any doses
​

## Description

The App should allow users to set up reminders for taking medication. These reminders should be triggered at the specified times and days for each medication.
​

## Acceptance Criteria

- [ ] The user can set reminders for each medication
- [ ] The reminders should be triggered at the corresponding times and days
- [ ] The user can enable or disable the reminders
- [ ] the app should send notifications to remind the user about medication intake
      ​

## Tasks

- [ ] create a user interface to set up medication reminders
- [ ] implement the functionality to trigger reminders at the specified times and days
- [ ] implement the ability to enable or disable reminders
- [ ] configure the app to send notifications for the reminders

**Comment by Katemuya** [comment]
LGTM 🚀
Very interesting US!

**Comment by rueveydaakuel** [comment]
> Just out of curiosity, how do you intend to implement the US? Is it through Backend?

I am still working with localStorage. I will try to do it this way.🙈

**Comment by Katemuya** [comment]
NICE! All the best 🥂
