### ISSUE TITLE
US-Image Upload

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#17]
## Value Proposition

**As a** user
**I want to** have the ability to upload images to my medication entries
**so that** I can capture important information or instructions in a visual format. 
​

## Description

<img width="423" alt="Bildschirmfoto 2023-07-05 um 15 53 11" src="https://github.com/rueveydaakuel/MediCeck/assets/130995493/4c4cf51b-f91b-466f-8600-bdb297a12b77">

​

## Acceptance Criteria

- [ ] There is an "Upload Image" button visible when creating a medication entry
- [ ] The user can click on the "Upload Image" button and select an image file from their device
- [ ] The selected image is added to the medication entry and associated with the specific medication
- [ ] The uploaded image is displayed on the medication entry card after saving the entry
- [ ] If no image is uploaded, the medication entry card should not display any placeholder or broken image icon
      ​

## Tasks

- [ ] In the medication entry there is a button "Datei auswählen" to chose and upload images
- [ ] Implement the functionality to allow the user to select an image file from their device when the "Upload Image" button is clicked
- [ ] Implement the functionality to display the uploaded image to the user before saving the entry
- [ ] e.g. Component Tests
- [ ] Update the medication entry card component to display the uploaded image along with the other medication details after the entry is saved
- [ ] Handle cases where no image is uploaded, ensuring that the medication entry card does not display any placeholder or broken image icon in such cases

**Comment by rueveydaakuel** [comment]
> Hi Rüveyda,
> 
> great idea to add an image upload for medications.
> 
> Just a little idea to make the first acceptance criteria more clear:
> 
> "There is an "Upload Image" button visible when creating a medication entry"
> 
> > the wireframe shows an "Datei auswählen" button, so you could change this to:
> > ' In the medication entry there is a button "Datei auswählen" to chose and upload images '
> 
> Cheers, Ronald

Thank you Ronald for your review  🙂 You are absolutely right. It is much clearer this way 🙌

**Comment by Danielschuetzle** [comment]
LGTM, great you implemented Ronalds suggestion 👍🏻
