### ISSUE TITLE
US - Edit or delete Uploaded Image

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#19]
## Value Proposition

**As a** user
**I want to** have the ability to edit or delete images in my medication entires
**so that** I can manage and update the visual information. 
​

## Description

In addition to the existing functionality of uploading images to medication entries, this user story introduces the ability to modify or remove uploaded images.

## Acceptance Criteria

- [ ]  For each uploaded image in a medication entry, there should be options to edit or delete the image
- [ ]  After editing or deleting an image, the changes should be saved and reflected in the medication entry

      
## Tasks

- [ ]  Update the editForm component to include buttons for editing and deleting images
- [ ] e Implement the functionality to allow the user to edit an uploaded image by selecting a new image file
- [ ]  Implement the functionality to delete an uploaded image from the entry
