### ISSUE TITLE
US 2: Medication Form

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#2]
## Value Proposition

**As a** user
**I want to** be able to enter the name of a person on the homepage
**so that** I can create the medication plan for this person
​

## Description

<img width="297" alt="Bildschirmfoto 2023-06-16 um 15 11 11" src="https://github.com/rueveydaakuel/MediCeck/assets/130995493/631b86a0-01a6-40fe-aa54-61243bea21ee">

## Acceptance Criteria

- [ ] On the home page there is an input field, where the name of a person
- [ ] After entering the name, the user can click on a "Next" button.

​
## Tasks

- [ ] Create a new file for the homepage component
- [ ] Add a heading to the homepage component
- [ ] Add a navigation bar to the homepage component
- [ ] Add an input field to the homepage component
- [ ] Add the "Next" button
- [ ] create a navbar

**Comment by actyvystom** [comment]
Hey Rüveyda, a nice start!
Anyway, some comments to consider:
- Your value proposition is too vague, it describes more or less the whole purpose of your app
- Try to step back and reduce to a clear and explicit functionality, e.g.
> As a planner (you could also stick to user)
> I want to see a list of persons I am responsible for their medication
> to be able to choose one to set their medication goals   
To set their medication goals would then be a following user story. 

Same applies to your **acceptance criteria** 
- keep it simple and start with adding a person 
- the definition of medication goals would then also be a part of a following user story. 

Also your scribble contains 3 navigation items, I assume that only one of it would make sense here for the time being.

**Comment by rueveydaakuel** [comment]
the user story is completely changed :)

**Comment by MariaRiosNavarro** [comment]
LGFM 🚀
