### ISSUE TITLE
US 1:  Show home page

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#3]
## Value Proposition
​
**As a** user
**I want to** see a list of people for whose medication I am responsible
**so that** I have an overview about their medication plans
​
## Description
​
<img width="368" alt="Bildschirmfoto 2023-06-16 um 16 36 10" src="https://github.com/rueveydaakuel/MediCeck/assets/130995493/2b08df21-f44d-47f6-bd44-4612f69a4516">

​
## Acceptance Criteria
​
- [ ] a headline with the app title "MediCheck" is displayed
- [ ] below the headline the data for each person and their medication is displayed
- [ ] the data for each person contains the name of the person and their medication schedule
- [ ] it is possible to see in detail when each person has to take their medication
- [ ] the data for each person are visually separated from each other by a border, so that it is easy to see which data belong together

## Tasks
​
- [ ] create a new branch `homePage`
- [ ] create a header
- [ ] A sample JSON file with the data for the people and their medications
- [ ] Create a component to display the list of people and their medications
- [ ] Display the sample data from the JSON file in the component.

**Comment by rueveydaakuel** [comment]
Changed in consultation with Mareike :)

**Comment by RonnySteady** [comment]
Hi Rüveyda, since you have a similar user story like me (list with cards) I would suggest:
- give your app a name (if you have one already) 
- the wireframe, criteria and tasks contains not only patients but also the medication so I would add the info about the medication in the value proposition 
- in tasks "A sample JSON file with the data for the people and their" the word medication is missing

**Comment by rueveydaakuel** [comment]
Hey Ronald, thank you very much for your feedback. Your comments are very good, I have taken them into account and adjusted the user story. With the App-name I am still undecided, have 2 in mind, just have to decide 🫠

**Comment by mbosselmann** [comment]
Hi Rüveyda,
your first user story looks good! I have some remarks for you for further improvement! 💪 

## Value proposition

**As a** user
**I want to** see a list of people for whose medication I am responsible
**so that** I have an overview about their medication plans

## Description
- I like your wireframe, but it would be nice to see more realistic data to understand your wireframe better.
- I also like Ronalds's remark about the app title. You can for now add the one you like more and then change the app name during the capstone time. :)
- I just thought that a footer for may not be necessary for now as you only habe one page or? 🤔 

## Acceptance criteria
- Instead of writing what "you" can see, I would explain what the user should see
  - a headline with the app title "your app name" is displayed
  - below the headline the data for each person and their medication is displayed
  - the data for each person contains the name of the person and their medication schedule
  - it is possible to see in detail when each person has to take their medication
  - the data for each person are visually separated from each other by a border, so that it is easy to see which data belong together

## Tasks
- For now I do not think that you need a home component. 🤔 
- And you also do not need a header component when you only want to render a `h1`. But that is up to you to decide. ;)
- you can add "create a feature branch" and optional add the name for your feature branch as task too.

I hope this does help! Feel free to ask me if you have further questions. :)

**Comment by rueveydaakuel** [comment]
Thank you Mareike for your feedback ☺️ I have now revised the user story with your suggestions :)

**Comment by FelineHuhn** [comment]
Nice progress Rüveyda 🚀
