### ISSUE TITLE
US 3: Medication Form

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#4]
## Value Proposition

**As a**  user
**I want to** create medication entries
**so that** I can manage their medication schedule effectively
​

## Description

<img width="371" alt="Bildschirmfoto 2023-06-16 um 15 59 38" src="https://github.com/rueveydaakuel/MediCeck/assets/130995493/82a35f8f-740e-45ed-ae8f-53bbaac021f3">
​

## Acceptance Criteria

- [ ] There are 7 buttons representing the days of the week
- [ ] There are 3 buttons representing different times of the day 
- [ ] Entries can be created for specific days, times, and medications
- [ ] The user must select a weekday to proceed
- [ ] The user must select a time of day to proceed
- [ ] There is an input field where the user can enter the name of the medication.
- [ ] The user must enter the name of the medication
- [ ] After saving, a medication entry card is generated with the entered information.
  ​

## Tasks

- [ ] Create a component for the medication entry form
- [ ]  Implement the 7 day buttons and ensure one is selected
- [ ] Implement the time buttons (morning, noon, evening) and ensure one is selected
- [ ] Add an input field for entering the medication name
- [ ] Implement the "Save" button functionality to generate a medication entry card
- [ ] Display the medication entry card after saving

**Comment by MariaRiosNavarro** [comment]
Maybe you should say that in the acceptance criteria, 
that the label must be visible on the screen, 
that an input must be visible, 
that the buttons for the days of the week must be shown with an initial...

(which is what you have to see on the screen for the form to be correct)

**Comment by MariaRiosNavarro** [comment]
And dont forget this issue:

"so that I can manage their medication schedule effectively"

**Comment by rueveydaakuel** [comment]
Thank you Maria for your helpful comments.
I have now revised the user story :)
