### ISSUE TITLE
US 4: Overview page

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#5]
## Value Proposition

**As a** user
**I want to** have an overview of the saved medication entries in the form of a list on a overview page
**so that** I can easily see all the medication entries for a person 
​

## Description

<img width="410" alt="Bildschirmfoto 2023-06-17 um 18 59 51" src="https://github.com/rueveydaakuel/MediCeck/assets/130995493/149cccbf-f5c3-4341-8fc3-42829c091a7c">
​

## Acceptance Criteria

- [ ] There is a overview page where all the saved medication entries are displayed in a list
- [ ] Each entry in the list shows the day, time, and name of the medication
- [ ] The entries are sorted chronologically, with the most recent entries at the top
- [ ] The list is scrollable if there are more entries than can fit on the page
- [ ] Each entry in the list is clickable, allowing the user to view/edit the details of the medication entry
      ​

## Tasks

- [ ] Create a overview page component
- [ ] Design the layout of the summary page to accommodate the list of medication entries
- [ ] Retrieve the saved medication entries from the storage or database
- [ ] Display the medication entries in a list format on the overview page
- [ ] Sort the entries chronologically with the most recent entries at the top
- [ ]  Make each entry clickable to view/edit the details of the medication entry

**Comment by MariaRiosNavarro** [comment]
Sorry Rüveyda, but does the Wireframe match the acceptance criteria? In the Wireframe I see boxes with names of people and what medications they take according to what part of the day. But in the acceptance criteria, do you mention that the Entries are ordered chronologically. How is that represented in the Wireframe? How can that be verified that the Entries are ordered chronologically?

**Comment by rueveydaakuel** [comment]
> Sorry Rüveyda, but does the Wireframe match the acceptance criteria? In the Wireframe I see boxes with names of people and what medications they take according to what part of the day. But in the acceptance criteria, do you mention that the Entries are ordered chronologically. How is that represented in the Wireframe? How can that be verified that the Entries are ordered chronologically?

Thank you Maria for your inquiry. I have formulated the criteria perhaps actually somewhat incomprehensibly. The idea behind is, that the entries should appear in an order. The last entry appears at the top of the list.

**Comment by MariaRiosNavarro** [comment]
Maybe you can put that explanation, that the newest one is up, in the description with the Wireframe. But with your clarification it's fine for me.🚀
