### ISSUE TITLE
US 5: edit medication entry card

### ISSUE THREAD

**Issue by rueveydaakuel** [rueveydaakuel/MediCeck#6]
## Value Proposition

**As a** user
**I want to** have the ability to edit a selected medication entry card
**so that** I can correct or make changes to the medication if needed 
​

## Description

<img width="716" alt="Bildschirmfoto 2023-06-17 um 20 01 48" src="https://github.com/rueveydaakuel/MediCeck/assets/130995493/841ac30c-56e1-4807-bc7e-5cb8902bc9c7">

​
## Acceptance Criteria

- [ ] When the user selects a medication entry card from the overview page, the detail page is opened
- [ ] The detail page displays all the information of the selected medication entry
- [ ] The user can edit the information, such as changing the day, time, or medication name
- [ ] After editing, the user can save the changes, and the update is reflected on the summary page
- [ ] The user has the option to cancel the edit without saving the changes
      ​

## Tasks

- [ ] Create a detail page component for editing a selected medication entry
- [ ] Open the detail page when the user selects a medication entry card
- [ ] Display all the information of the selected medication entry on the detail page
- [ ] Implement editing functions to allow the user to make changes to the information
- [ ] Implement the save function to store the updated information
- [ ] Update the overview page after saving to reflect the changes
- [ ] Add a cancel function to allow the user to cancel the edit without saving the changes

**Comment by MariaRiosNavarro** [comment]
I think maybe instead of "Create a detail page component for editing a medication entry" it should be "Create a detail page component for editing a selected medication entry" to focus on editing a selected medication entry.

**Comment by rueveydaakuel** [comment]
> I think maybe instead of "Create a detail page component for editing a medication entry" it should be "Create a detail page component for editing a selected medication entry" to focus on editing a selected medication entry.

Thank you for the tip Maria:) 
I have improved the task description
